apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-microservice-deployment
  labels:
    app: quarkus-rest-api-couchdb
spec:
  selector:
    matchLabels:
      app: quarkus-rest-api-couchdb
  template:
    metadata:
      labels:
        app: quarkus-rest-api-couchdb
    spec:
      containers:
        - name: quarkus-rest-api-couchdb-container
          image: samihaddouti/quarkus-rest-api-couchdb:latest
          ports:
            - containerPort: 8080
          env:
          - name: COUCHDB_USER
            valueFrom:
              secretKeyRef:
                name: quarkus-rest-api-couchdb-secret
                key: COUCHDB_USER
          - name: COUCHDB_PWORD
            valueFrom:
              secretKeyRef:
                name: quarkus-rest-api-couchdb-secret
                key: COUCHDB_PWORD
          - name: COUCHDB_ADDRESS
            value: "couchdb"
          - name: COUCHDB_PORT
            value: "5984"
---